# 工作流程的名字
name: Build and Release apk

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 这个工作流程需要执行的任务
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v3
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@main
        with:
          channel: "stable"
      # 下载项目依赖
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - name: Release apk
        run: flutter build apk --release
        working-directory: example
      # 发布到 Release
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: example/build/app/outputs/apk/release/app-release.apk
      # 下载编译
      - name: Download APK from build
          uses: actions/download-artifact@v2
          with:
            name: apk
            - name: Display structure of downloaded files
              run: ls -R
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1.1.4
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: ${{ github.ref }}
            - name: Upload Release APK
              id: upload_release_asset
              uses: actions/upload-release-asset@v1.0.1
              env:
                GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: ./app-release.apk
                asset_name: app-release.apk
                asset_content_type: application/zip
