# 工作流程的名字
name: Test And Build

# 工作流程触发的时机，这里是当一个版本标签推送到仓库时触发
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 这个工作流程需要执行的任务
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    # 这个任务的步骤
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v3
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@main
        with:
          channel: "stable"
      # 下载项目依赖
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - name: Release apk
        run: flutter build apk --release
        working-directory: example
