name: Publish Package

# 监听版本号变化
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  # 推送操作
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!
      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{secrets.RElEASE_TOKEN }}
          refreshToken: ${{secrets.REFRESH_TOKEN }}
          skipTests: true
          force: true
  # Release 操作
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      discussions: write
    steps:
      # 拉取项目代码
      - uses: actions/checkout@v3
      # 建立 java 环境
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      # 建立 Flutter 环境
      - name: Flutter action
        uses: subosito/flutter-action@main
        with:
          channel: "stable"
      # 下载项目依赖
      - run: flutter pub get
      # 执行测试
      - run: flutter test
      # 打包 APK
      - name: Build Release apk
        run: flutter build apk --release
        working-directory: example
      # 发布到 上次文件至artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: example/build/app/outputs/apk/release/app-release.apk
      # 创建 Release
      - name: Create a Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "example/build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.ACCOUNT_TOKEN }}
          allowUpdates: true
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          bodyFile: "release.md"