name: Publish to Pub.dev

on:
  pull_request:
    branches:
      - master

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{secrets.RElEASE_TOKEN }}
          refreshToken: ${{secrets.OAUTH_REFRESH_TOKEN }}
          skipTests: true
          force: true