name: Publish to pub.dev

#on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+*'

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!

      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{secrets.RElEASE_TOKEN }}
          refreshToken: ${{secrets.REFRESH_TOKEN }}
          skipTests: true
          force: true